#!/usr/bin/env python3
"""
List all databases in MongoDB
"""

import pymongo

def list_databases():
    # Connect to MongoDB
    client = pymongo.MongoClient('mongodb://localhost:27017/')

    # List all databases
    db_list = client.list_database_names()

    # Print the list of databases
    for db in db_list:
        print(db)

if __name__ == "__main__":
    list_databases()
